name: CI/CD Pipeline

# 워크플로우 트리거 설정
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # (이전 코드는 변경 없음)

  sonarcloud:
    # (이전 코드는 변경 없음)

  create_release:
    # (이전 코드는 변경 없음)

  generate_docs:
    runs-on: ubuntu-latest
    needs: build 
    permissions:
      contents: write 
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Doxygen 
      run: sudo apt-get install doxygen -y
    
    - name: Generate Documentation  # 여기서 콜론 하나만 사용
      run: |
        doxygen Doxyfile
        if [ ! -f docs/index.html ]; then 
          echo '<meta http-equiv="refresh" content="0; url=./html/index.html">' > docs/index.html 
        fi
    
    - name: Deploy to GitHub Pages  # 여기서 콜론 하나만 사용
      uses: peaceiris/actions-gh-pages@v3  # 여기서 콜론 하나만 사용
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}  # 여기서 콜론 하나만 사용
        publish_dir: ./docs  # 여기서 콜론 하나만 사용
